### ISSUE TITLE
tutorial/result_handler not works

### ISSUE THREAD

**Issue by zhaofeng-shu33** [elki-project/elki-project.github.io#1]
For version 0.75 of ELKI, the first parameter of `ResultUtil.filterResults` is changed to accept `ResultHierarchy`.  I believe the tutorial is out of date.

**Comment by kno10** [comment]
Yes, as the website says the tutorial is last updated 20141030.

**Comment by zhaofeng-shu33** [comment]
Any plan to update the website?

**Comment by kno10** [comment]
Sorry, no. This is easy to figure out, and it will change in 0.8, so it will become obsolete again anyway.

**Comment by kno10** [comment]
This tutorial has been updated. https://elki-project.github.io/tutorial/result_handler
